### ISSUE TITLE
ISSUE-234: Cannot build the project

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-client-go#52]
Original Issue: apache/pulsar-client-go#234 

---

#### Expected behavior

The client in this repository should build.
#### Actual behavior

An error appears when trying to build the client:
```
./c_go_pulsar.h:22:10: fatal error: pulsar/c/client.h: No such file or directory
```

#### Steps to reproduce

run 
```
go build ./pulsar
```
#### System configuration
**Pulsar version**:  v0.1.0

**Comment by wolfstudy** [comment]
done
