### ISSUE TITLE
ISSUE-243: Expose isReplicated and replicatedFrom for Pulsar message.

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-client-go#60]
Original Issue: apache/pulsar-client-go#243 

---

**Is your feature request related to a problem? Please describe.**
It's better to expose `isReplicated` and `replicatedFrom` for the Pulsar message. We can use these two properties to judge whether the message is replicated from the remote cluster.

**Comment by wolfstudy** [comment]
https://github.com/apache/pulsar-client-go/pull/251/files
