### ISSUE TITLE
ISSUE-244: Memory Leak zstdProvider.Decompress

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsar-client-go#61]
Original Issue: apache/pulsar-client-go#244 

---

The current implementation of `zstdProvider.Decompress` doesn't close the zstd decoder and will lead to memory leak.

https://github.com/apache/pulsar-client-go/blob/e7f1673350f208b5063823282d14906d70d66904/pulsar/internal/compression/zstd.go#L45-L60

There should be a `defer d.Close()` at line 50 according to the document: https://github.com/klauspost/compress/tree/master/zstd#usage-1

However, I would suggest just use the `decoder.DecodeAll` to implement `zstdProvider.Decompress` and reuse the decoder.

**Comment by goku321** [comment]
Can I work on this?

**Comment by sijie** [comment]
@goku321 yes feel free to take this item by leaving the comment of "I am working on this". So other people will know that you are working on it.

**Comment by goku321** [comment]
Thanks @sijie  , will start working on this issue.
